name: GitHub Webhook Trigger

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          EVENT_TYPE="${{ github.event_name }}"
          PAYLOAD=$(cat $GITHUB_EVENT_PATH)
          
          # Calculate HMAC signature
          SIGNATURE="sha1=$(echo -n "$PAYLOAD" | openssl dgst -sha1 -hmac "$WEBHOOK_SECRET" | cut -d' ' -f2)"
          
          # Send webhook
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: $EVENT_TYPE" \
            -H "X-Hub-Signature: $SIGNATURE" \
            -d "@$GITHUB_EVENT_PATH" 